// Login Dispatch States
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";
export const AUTHENTICATED_SUCCESS = "AUTHENTICATED_SUCCESS";
export const AUTHENTICATED_FAIL = "AUTHENTICATED_FAIL";

// Register Dispatch States
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const CLEAR_MESSAGE_REGISTER = "CLEAR_MESSAGE_REGISTER";

// Settings & Verify Dispatch States
export const VERIFY_EMAIL_SUCCESS = "VERIFY_EMAIL_SUCCESS";

export const CHANGE_EMAIL_SUCCESS = "CHANGE_EMAIL_SUCCESS";
export const JUST_CHANGE_EMAIL_SUCCESS = "JUST_CHANGE_EMAIL_SUCCESS";

export const CHANGE_USERNAMME_SUCCESS = "CHANGE_USERNAMME_SUCCESS";

export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";

// User Dispatch States
export const LOAD_MEOW_STORE = "LOAD_MEOW_STORE";
export const LOAD_MEOW_SUCCESS = "LOAD_MEOW_SUCCESS";
export const LOAD_MEOW_FAIL = "LOAD_MEOW_FAIL";
export const LOAD_LEARNING_SUCCESS = "LOAD_LEARNING_SUCCESS";

export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";

// Course Dispatch States
export const ENROLL_COURSE_SUCCESS = "ENROLL_COURSE_SUCCESS";
export const REMOVE_COURSE_SUCCESS = "REMOVE_COURSE_SUCCESS";

export const LOAD_COURSES_SUCCESS = "LOAD_COURSES_SUCCESS";
export const LOAD_COURSES_FAIL = "LOAD_COURSES_FAIL";

export const LOAD_LANGUAGES_SUCCESS = "LOAD_LANGUAGES_SUCCESS";

export const UPDATE_VOICE_SPEED = "UPDATE_VOICE_SPEED";
export const UPDATE_VOICE_PITCH = "UPDATE_VOICE_PITCH";
export const UPDATE_VOICE_VOLUME = "UPDATE_VOICE_VOLUME";

export const UPDATE_USED_STORE = "UPDATE_USED_STORE";
export const UPDATE_VOICES_STORE = "UPDATE_VOICES_STORE";

export const LOAD_VOICES_SUCCESS = "LOAD_VOICES_SUCCESS";

// Categories Dispatch States
export const LOAD_CATEGORIES_STORE = "LOAD_CATEGORIES_STORE";
export const LOAD_CATEGORIES_SUCCESS = "LOAD_CATEGORIES_SUCCESS";
export const LOAD_CATEGORIES_FAIL = "LOAD_CATEGORIES_FAIL";

// Collection Dispatch States
export const LOAD_COLLECTIONS_LEARNING_SUCCESS =
  "LOAD_COLLECTIONS_LEARNING_SUCCESS";
export const LOAD_COLLECTIONS_LEARNING_FAIL = "LOAD_COLLECTIONS_LEARNING_FAIL";

export const LOAD_COLLECTION_SUCCESS = "LOAD_COLLECTION_SUCCESS";
export const CREATE_COLLECTION_SUCCESS = "CREATE_COLLECTION_SUCCESS";
export const LEARN_COLLECTION_SUCCESS = "LEARN_COLLECTION_SUCCESS";

export const REMOVE_COLLECTION_SUCCESS = "REMOVE_COLLECTION_SUCCESS";
export const DELETE_COLLECTION_SUCCESS = "DELETE_COLLECTION_SUCCESS";

export const LOAD_REVIEW_COLLECTION_SUCCESS = "LOAD_REVIEW_COLLECTION_SUCCESS";
export const POST_REVIEW_COLLECTION_SUCCESS = "POST_REVIEW_COLLECTION_SUCCESS";
export const UPDATE_REVIEW_COLLECTION_SUCCESS =
  "UPDATE_REVIEW_COLLECTION_SUCCESS";

// Unit Dispatch States
export const MANAGE_UNIT_SUCCESS = "MANAGE_UNIT_SUCCESS";

// Dictionary Dispatch States
export const LOAD_WORDS_SUCCESS = "LOAD_WORDS_SUCCESS";
export const LOAD_PHRASES_SUCCESS = "LOAD_PHRASES_SUCCESS";
export const LOAD_SENTENCES_SUCCESS = "LOAD_SENTENCES_SUCCESS";

// Word Dispatch States
export const UPDATE_WORDS_IN_COLLECTION = "UPDATE_WORDS_IN_COLLECTION";

export const UPDATE_POINTS_IN_COLLECTION = "UPDATE_POINTS_IN_COLLECTION";
export const UPDATE_POINTS_IN_LEARNED = "UPDATE_POINTS_IN_LEARNED";

// Word Translation Dispatch States
export const SEARCH_WORD_TRAN_SUCCESS = "SEARCH_WORD_TRAN_SUCCESS";
export const CREATE_WORD_TRAN_SUCCESS = "CREATE_WORD_TRAN_SUCCESS";
export const UPDATE_WORD_TRAN_SUCCESS = "UPDATE_WORD_TRAN_SUCCESS";
export const DELETE_WORD_TRAN_SUCCESS = "DELETE_WORD_TRAN_SUCCESS";

export const USE_WORD_TRAN_SUCCESS = "USE_WORD_TRAN_SUCCESS";
export const REMOVE_WORD_TRAN_SUCCESS = "REMOVE_WORD_TRAN_SUCCESS";

// Phrase Dispatch States
export const UPDATE_PHRASES_IN_COLLECTION = "UPDATE_PHRASES_IN_COLLECTION";

// Sentence Dispatch States
export const UPDATE_SENTENCES_IN_COLLECTION = "UPDATE_SENTENCES_IN_COLLECTION";
