# Generated by Django 3.2 on 2022-02-10 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='thumbnail_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('vi', 'Vietnamese'), ('de', 'German'), ('ja', 'Japanese')], max_length=5, unique=True),
        ),
    ]
