# Generated by Django 3.2 on 2022-02-11 03:19

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_category'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='profile',
        #     name='avatar',
        #     field=models.ImageField(default='avatars/default/default.webp', upload_to=base.models.avatar_uploads2),
        # ),
    ]
