# Generated by Django 3.2 on 2022-02-11 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_profile_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='thumbnail_url',
            new_name='banner_url',
        ),
    ]
