# Generated by Django 3.2 on 2022-02-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20220214_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phrase_trans_using',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_using_phrase_trans', through='base.PhraseTransUsing', to='base.PhraseTranslation'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sentence_trans_using',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_using_sentence_trans', through='base.SentenceTransUsing', to='base.SentenceTranslation'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='word_trans_using',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_using_word_trans', through='base.WordTransUsing', to='base.WordTranslation'),
        ),
    ]
