# Generated by Django 3.2 on 2022-02-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_lesson_unknown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='unknown',
        ),
        migrations.AddField(
            model_name='lesson',
            name='unknown_phrases',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='unknown_sentences',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='unknown_words',
            field=models.TextField(blank=True, null=True),
        ),
    ]
