# Generated by Django 4.0.3 on 2022-03-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_profile_phrase_trans_using_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phrase_trans_using',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_using_phrase_trans', through='base.PhraseTransUsing', to='base.phrasetranslation'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sentence_trans_using',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_using_sentence_trans', through='base.SentenceTransUsing', to='base.sentencetranslation'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='word_trans_using',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_using_word_trans', through='base.WordTransUsing', to='base.wordtranslation'),
        ),
    ]
