# Generated by Django 4.0.3 on 2022-04-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_profile_phrase_trans_using_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phrasetranslation',
            name='ipa',
        ),
        migrations.RemoveField(
            model_name='phrasetranslation',
            name='translations',
        ),
        migrations.RemoveField(
            model_name='sentencetranslation',
            name='ipa',
        ),
        migrations.RemoveField(
            model_name='sentencetranslation',
            name='translations',
        ),
        migrations.RemoveField(
            model_name='wordtranslation',
            name='ipa',
        ),
        migrations.RemoveField(
            model_name='wordtranslation',
            name='translations',
        ),
        migrations.AddField(
            model_name='phrasetranslation',
            name='translation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sentencetranslation',
            name='translation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wordtranslation',
            name='translation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
