# Generated by Django 4.0.3 on 2022-04-10 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_phrasetranslation_ipa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='tips',
            new_name='documents',
        ),
    ]
