# Generated by Django 4.0.3 on 2022-04-15 16:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0014_courselearning_lessonslearning_newword_phraselearned_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LessonsLearning',
            new_name='LessonLearning',
        ),
        migrations.AlterModelTable(
            name='lessonlearning',
            table='duoduo_lesson_learning',
        ),
    ]
