# Generated by Django 4.0.3 on 2022-04-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_phrasetranslation_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='courses_learning',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phrases_learned',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sentences_learned',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='words_learned',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='documents',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='phrases',
        ),
        migrations.AddField(
            model_name='lesson',
            name='phrases',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='sentences',
        ),
        migrations.AddField(
            model_name='lesson',
            name='sentences',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='topics',
        ),
        migrations.AddField(
            model_name='lesson',
            name='topics',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='unknown_phrases',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='unknown_sentences',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='unknown_words',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='words',
        ),
        migrations.AddField(
            model_name='lesson',
            name='words',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
