# Generated by Django 4.0.3 on 2022-04-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_profile_course_learning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='course_learning',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lessons_learning',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
