# Generated by Django 4.0.3 on 2022-05-01 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_lesson_documents_alter_lesson_phrases_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lessons_created',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phrase_trans_created',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sentence_trans_created',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='word_trans_created',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
