# Generated by Django 4.0.3 on 2022-05-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_profile_lessons_created_profile_phrase_trans_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrasetranslation',
            name='translation',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='sentencetranslation',
            name='translation',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='wordtranslation',
            name='translation',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
