# Generated by Django 4.0.3 on 2022-05-06 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_remove_lesson_documents_remove_lesson_phrases_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='documents',
            field=models.ManyToManyField(blank=True, null=True, to='base.document'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='phrases',
            field=models.ManyToManyField(blank=True, null=True, to='base.phrase'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='sentences',
            field=models.ManyToManyField(blank=True, null=True, to='base.sentence'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='topics',
            field=models.ManyToManyField(blank=True, null=True, to='base.topic'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='words',
            field=models.ManyToManyField(blank=True, null=True, to='base.word'),
        ),
        migrations.AddField(
            model_name='profile',
            name='course_learning',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.course'),
        ),
    ]
