# Generated by Django 4.0.3 on 2022-05-10 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_lesson_documents_lesson_phrases_lesson_sentences_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courselearning',
            old_name='phrases_learned',
            new_name='num_phrases_learned',
        ),
        migrations.RenameField(
            model_name='courselearning',
            old_name='sentences_learned',
            new_name='num_sentences_learned',
        ),
        migrations.RenameField(
            model_name='courselearning',
            old_name='story_read',
            new_name='num_stories_read',
        ),
        migrations.RenameField(
            model_name='courselearning',
            old_name='words_learned',
            new_name='num_words_learned',
        ),
        migrations.AddField(
            model_name='language',
            name='language_code',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('vi', 'Vietnamese'), ('de', 'German'), ('ja', 'Japanese')], max_length=5, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(max_length=220, unique=True),
        ),
    ]
