# Generated by Django 4.0.3 on 2022-06-04 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_rename_phrases_learned_courselearning_num_phrases_learned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='use_space',
            field=models.BooleanField(default=False),
        ),
    ]
