# Generated by Django 4.0.3 on 2022-07-24 01:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_language_use_space'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='document',
            name='language',
        ),
        migrations.RemoveField(
            model_name='language',
            name='num_lessons',
        ),
        migrations.RemoveField(
            model_name='language',
            name='num_phrases',
        ),
        migrations.RemoveField(
            model_name='language',
            name='num_sentences',
        ),
        migrations.RemoveField(
            model_name='language',
            name='num_words',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='phrases',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='sentences',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='topics',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='words',
        ),
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='phrasetranusing',
            name='date_used',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='courses_learning',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='learned',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='sentencetranusing',
            name='date_used',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wordtranusing',
            name='date_used',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='language',
            name='use_space',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='CourseLearning',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
