# Generated by Django 4.0.3 on 2022-07-24 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_lesson_documents_lesson_phrases_lesson_sentences_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
