# Generated by Django 4.0.6 on 2022-08-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_learned_learnedlog_remove_sentencelearned_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnedlog',
            name='time_ms',
            field=models.IntegerField(blank=True, default=1659800352412, null=True),
        ),
    ]
