# Generated by Django 4.0.6 on 2022-08-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_alter_learnedlog_time_ms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnedlog',
            name='time_ms',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
