# Generated by Django 4.0.6 on 2022-08-06 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0034_alter_learnedlog_time_ms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Learned',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.JSONField(blank=True, default=list, null=True)),
                ('phrases', models.JSONField(blank=True, default=list, null=True)),
                ('sentences', models.JSONField(blank=True, default=list, null=True)),
                ('language', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.language')),
                ('learner', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'duoduo_learned',
            },
        ),
        migrations.RemoveField(
            model_name='sentencelearned',
            name='language',
        ),
        migrations.RemoveField(
            model_name='sentencelearned',
            name='sentence',
        ),
        migrations.RemoveField(
            model_name='sentencelearned',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wordlearned',
            name='language',
        ),
        migrations.RemoveField(
            model_name='wordlearned',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wordlearned',
            name='word',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='learned',
        ),
        migrations.AlterField(
            model_name='learnedlog',
            name='time_ms',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='banner_url',
            field=models.TextField(blank=True, max_length=2020, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='documents',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='phrases',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='sentences',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='topics',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='unknown_phrases',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='unknown_sentences',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='unknown_words',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='words',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='courses_learning',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.DeleteModel(
            name='PhraseLearned',
        ),
        migrations.DeleteModel(
            name='SentenceLearned',
        ),
        migrations.DeleteModel(
            name='WordLearned',
        ),
    ]
