# Generated by Django 4.0.6 on 2022-08-08 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_lessonlearning_date_learned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phrasetranusing',
            name='course',
        ),
        migrations.RemoveField(
            model_name='phrasetranusing',
            name='phrase',
        ),
        migrations.RemoveField(
            model_name='sentencetranusing',
            name='course',
        ),
        migrations.RemoveField(
            model_name='sentencetranusing',
            name='sentence',
        ),
        migrations.RemoveField(
            model_name='wordtranusing',
            name='course',
        ),
        migrations.RemoveField(
            model_name='wordtranusing',
            name='word',
        ),
    ]
