# Generated by Django 4.0.6 on 2022-08-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_profile_email_profile_email_verified_profile_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.TextField(blank=True, max_length=2020, null=True),
        ),
    ]
