# Generated by Django 4.0.6 on 2022-08-20 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_verification_is_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verification',
            old_name='is_complete',
            new_name='is_completed',
        ),
    ]
