# Generated by Django 4.0.6 on 2022-09-23 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_rename_is_complete_verification_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
    ]
