# Generated by Django 4.0.6 on 2022-09-23 01:58

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_remove_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatars/default/default.webp', upload_to=base.models.avatar_uploads2),
        ),
    ]
