# Generated by Django 4.0.6 on 2022-10-19 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0045_profile_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='courses_learning',
            new_name='courses_learning_ids',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_code',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='phrases',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='sentences',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='unknown_phrases',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='unknown_sentences',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='unknown_words',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='words',
        ),
        migrations.AlterField(
            model_name='course',
            name='language_learning',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.language'),
        ),
        migrations.AlterField(
            model_name='course',
            name='language_speaking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.language'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.language'),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=220, null=True)),
                ('description', models.CharField(blank=True, max_length=220, null=True)),
                ('words', models.JSONField(blank=True, default=list, null=True)),
                ('phrases', models.JSONField(blank=True, default=list, null=True)),
                ('sentences', models.JSONField(blank=True, default=list, null=True)),
                ('unknown_words', models.JSONField(blank=True, default=list, null=True)),
                ('unknown_phrases', models.JSONField(blank=True, default=list, null=True)),
                ('unknown_sentences', models.JSONField(blank=True, default=list, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.lesson')),
            ],
            options={
                'db_table': 'duoduo_unit',
            },
        ),
    ]
