# Generated by Django 4.0.6 on 2022-10-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_rename_courses_learning_profile_courses_learning_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='phrase_ids',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='sentence_ids',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='word_ids',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
