# Generated by Django 4.1.2 on 2022-11-08 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0047_language_phrase_ids_language_sentence_ids_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Moderator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=220, unique=True)),
                (
                    "course",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.course",
                    ),
                ),
            ],
            options={
                "db_table": "duoduo_moderator",
            },
        ),
        migrations.CreateModel(
            name="PhraseRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phrase", models.CharField(max_length=220, unique=True)),
                ("translation", models.JSONField(blank=True, default=dict, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("type_status", models.PositiveSmallIntegerField(default=0)),
                ("response", models.TextField(blank=True, max_length=2020, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.language",
                    ),
                ),
            ],
            options={
                "db_table": "duoduo_phrase_request",
            },
        ),
        migrations.CreateModel(
            name="PhraseTranRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now=True)),
                ("request", models.TextField(blank=True, max_length=2020, null=True)),
                ("type_status", models.PositiveSmallIntegerField(default=0)),
                ("response", models.TextField(blank=True, max_length=2020, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "duoduo_phrase_translation_request",
            },
        ),
        migrations.CreateModel(
            name="PhraseTranRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now=True)),
                ("translation", models.JSONField(blank=True, default=dict, null=True)),
                ("type_status", models.PositiveSmallIntegerField(default=0)),
                ("response", models.TextField(blank=True, max_length=2020, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "duoduo_phrase_translation_revision",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=220, unique=True)),
                (
                    "course",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.course",
                    ),
                ),
            ],
            options={
                "db_table": "duoduo_role",
            },
        ),
        migrations.CreateModel(
            name="SentenceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sentence", models.CharField(max_length=220, unique=True)),
                ("translation", models.JSONField(blank=True, default=dict, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("type_status", models.PositiveSmallIntegerField(default=0)),
                ("response", models.TextField(blank=True, max_length=2020, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.language",
                    ),
                ),
            ],
            options={
                "db_table": "duoduo_sentence_request",
            },
        ),
        migrations.CreateModel(
            name="SentenceTranRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now=True)),
                ("request", models.TextField(blank=True, max_length=2020, null=True)),
                ("type_status", models.PositiveSmallIntegerField(default=0)),
                ("response", models.TextField(blank=True, max_length=2020, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "duoduo_sentence_translation_request",
            },
        ),
        migrations.CreateModel(
            name="SentenceTranRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now=True)),
                ("translation", models.JSONField(blank=True, default=dict, null=True)),
                ("type_status", models.PositiveSmallIntegerField(default=0)),
                ("response", models.TextField(blank=True, max_length=2020, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "duoduo_sentence_translation_revision",
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_subscribed", models.DateTimeField(auto_now_add=True)),
                ("date_expired", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "duoduo_subscription",
            },
        ),
        migrations.CreateModel(
            name="UserModerator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moderator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.moderator"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "duoduo_user_moderator",
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.role"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "duoduo_user_role",
            },
        ),
        migrations.CreateModel(
            name="WordRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=220, unique=True)),
                ("translation", models.JSONField(blank=True, default=dict, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("type_status", models.PositiveSmallIntegerField(default=0)),
                ("response", models.TextField(blank=True, max_length=2020, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.language",
                    ),
                ),
            ],
            options={
                "db_table": "duoduo_word_request",
            },
        ),
        migrations.CreateModel(
            name="WordTranRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now=True)),
                ("request", models.TextField(blank=True, max_length=2020, null=True)),
                ("type_status", models.PositiveSmallIntegerField(default=0)),
                ("response", models.TextField(blank=True, max_length=2020, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "duoduo_word_translation_request",
            },
        ),
        migrations.CreateModel(
            name="WordTranRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now=True)),
                ("translation", models.JSONField(blank=True, default=dict, null=True)),
                ("type_status", models.PositiveSmallIntegerField(default=0)),
                ("response", models.TextField(blank=True, max_length=2020, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "duoduo_word_translation_revision",
            },
        ),
        migrations.RemoveField(
            model_name="phrase",
            name="topics",
        ),
        migrations.RemoveField(
            model_name="phrasetranusing",
            name="date_used",
        ),
        migrations.RemoveField(
            model_name="sentence",
            name="topics",
        ),
        migrations.RemoveField(
            model_name="sentencetranusing",
            name="date_used",
        ),
        migrations.RemoveField(
            model_name="word",
            name="topics",
        ),
        migrations.RemoveField(
            model_name="wordtranusing",
            name="date_used",
        ),
        migrations.AddField(
            model_name="phrase",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="phrasetranslation",
            name="credits",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="phrasetranslation",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="sentence",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="sentencetranslation",
            name="credits",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sentencetranslation",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="word",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="wordtranslation",
            name="credits",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="wordtranslation",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="verification",
            name="type_verification",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="NewWord",
        ),
        migrations.AddField(
            model_name="wordtranrequest",
            name="translation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="base.wordtranslation"
            ),
        ),
        migrations.AddField(
            model_name="sentencetranrequest",
            name="translation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="base.sentencetranslation",
            ),
        ),
        migrations.AddField(
            model_name="phrasetranrequest",
            name="translation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="base.phrasetranslation"
            ),
        ),
    ]
