# Generated by Django 4.1.2 on 2022-11-08 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0048_moderator_phraserequest_phrasetranrequest_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="phrasetranrevision",
            name="translation_id",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.phrasetranslation",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sentencetranrevision",
            name="translation_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.sentencetranslation",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wordtranrevision",
            name="translation_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.wordtranslation",
            ),
            preserve_default=False,
        ),
    ]
