# Generated by Django 4.1.2 on 2022-11-08 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0049_phrasetranrevision_translation_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="phrasetranrevision",
            name="translation_id",
        ),
        migrations.RemoveField(
            model_name="sentencetranrevision",
            name="translation_id",
        ),
        migrations.RemoveField(
            model_name="wordtranrevision",
            name="translation_id",
        ),
        migrations.AddField(
            model_name="phrasetranrevision",
            name="new_translation",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="sentencetranrevision",
            name="new_translation",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="wordtranrevision",
            name="new_translation",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="phrasetranrevision",
            name="translation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="base.phrasetranslation"
            ),
        ),
        migrations.AlterField(
            model_name="sentencetranrevision",
            name="translation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="base.sentencetranslation",
            ),
        ),
        migrations.AlterField(
            model_name="wordtranrevision",
            name="translation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="base.wordtranslation"
            ),
        ),
    ]
