# Generated by Django 4.1.2 on 2022-11-08 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0050_remove_phrasetranrevision_translation_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="phrasetranrevision",
            name="new_translation",
        ),
        migrations.RemoveField(
            model_name="phrasetranrevision",
            name="translation",
        ),
        migrations.RemoveField(
            model_name="sentencetranrevision",
            name="new_translation",
        ),
        migrations.RemoveField(
            model_name="sentencetranrevision",
            name="translation",
        ),
        migrations.RemoveField(
            model_name="wordtranrevision",
            name="new_translation",
        ),
        migrations.RemoveField(
            model_name="wordtranrevision",
            name="translation",
        ),
    ]
