# Generated by Django 4.1.2 on 2022-11-08 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0051_remove_phrasetranrevision_new_translation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="phrasetranrevision",
            name="new_translation",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="phrasetranrevision",
            name="translation",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.phrasetranslation",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sentencetranrevision",
            name="new_translation",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="sentencetranrevision",
            name="translation",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.sentencetranslation",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wordtranrevision",
            name="new_translation",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="wordtranrevision",
            name="translation",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.wordtranslation",
            ),
            preserve_default=False,
        ),
    ]
