# Generated by Django 4.1.2 on 2022-11-09 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0052_phrasetranrevision_new_translation_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wordtranslation",
            old_name="credits",
            new_name="num_credits",
        ),
        migrations.RemoveField(
            model_name="phrasetranrevision",
            name="response",
        ),
        migrations.RemoveField(
            model_name="phrasetranrevision",
            name="type_status",
        ),
        migrations.RemoveField(
            model_name="sentencetranrevision",
            name="response",
        ),
        migrations.RemoveField(
            model_name="sentencetranrevision",
            name="type_status",
        ),
        migrations.RemoveField(
            model_name="wordtranrevision",
            name="response",
        ),
        migrations.RemoveField(
            model_name="wordtranrevision",
            name="type_status",
        ),
    ]
