# Generated by Django 4.1.2 on 2022-11-09 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0053_rename_credits_wordtranslation_num_credits_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewPhrase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phrase", models.CharField(max_length=220, unique=True)),
                ("translation", models.JSONField(blank=True, default=dict, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("num_credits", models.IntegerField(default=0)),
                ("type_status", models.PositiveSmallIntegerField(default=0)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.language",
                    ),
                ),
            ],
            options={
                "db_table": "duoduo_new_phrase",
            },
        ),
        migrations.CreateModel(
            name="NewPhraseCredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vote", models.BooleanField(default=False)),
                (
                    "phrase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.newphrase"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "duoduo_new_phrase_credit",
            },
        ),
        migrations.CreateModel(
            name="NewSentence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sentence", models.CharField(max_length=220, unique=True)),
                ("translation", models.JSONField(blank=True, default=dict, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("num_credits", models.IntegerField(default=0)),
                ("type_status", models.PositiveSmallIntegerField(default=0)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.language",
                    ),
                ),
            ],
            options={
                "db_table": "duoduo_new_sentence",
            },
        ),
        migrations.CreateModel(
            name="NewSentenceCredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vote", models.BooleanField(default=False)),
                (
                    "sentence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.newsentence",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "duoduo_new_sentence_credit",
            },
        ),
        migrations.CreateModel(
            name="NewWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=220, unique=True)),
                ("translation", models.JSONField(blank=True, default=dict, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("num_credits", models.IntegerField(default=0)),
                ("type_status", models.PositiveSmallIntegerField(default=0)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.language",
                    ),
                ),
            ],
            options={
                "db_table": "duoduo_new_word",
            },
        ),
        migrations.CreateModel(
            name="NewWordCredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vote", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.newword"
                    ),
                ),
            ],
            options={
                "db_table": "duoduo_new_word_credit",
            },
        ),
        migrations.CreateModel(
            name="PhraseTranCredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vote", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "duoduo_phrase_translation_credit",
            },
        ),
        migrations.CreateModel(
            name="PhraseTranResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_responsed", models.DateTimeField(auto_now=True)),
                ("response", models.TextField(blank=True, max_length=2020, null=True)),
                ("type_status", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "db_table": "duoduo_phrase_translation_response",
            },
        ),
        migrations.CreateModel(
            name="SentenceTranCredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vote", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "duoduo_sentence_translation_credit",
            },
        ),
        migrations.CreateModel(
            name="SentenceTranResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_responsed", models.DateTimeField(auto_now=True)),
                ("response", models.TextField(blank=True, max_length=2020, null=True)),
                ("type_status", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "db_table": "duoduo_sentence_translation_response",
            },
        ),
        migrations.CreateModel(
            name="WordTranCredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vote", models.BooleanField(default=False)),
                (
                    "translation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.wordtranslation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "duoduo_word_translation_credit",
            },
        ),
        migrations.CreateModel(
            name="WordTranResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_responsed", models.DateTimeField(auto_now=True)),
                ("response", models.TextField(blank=True, max_length=2020, null=True)),
                ("type_status", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "db_table": "duoduo_word_translation_response",
            },
        ),
        migrations.RemoveField(
            model_name="sentencerequest",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="sentencerequest",
            name="language",
        ),
        migrations.RemoveField(
            model_name="wordrequest",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="wordrequest",
            name="language",
        ),
        migrations.RenameField(
            model_name="phrasetranrequest",
            old_name="date_created",
            new_name="date_requested",
        ),
        migrations.RenameField(
            model_name="phrasetranrequest",
            old_name="creator",
            new_name="requestor",
        ),
        migrations.RenameField(
            model_name="phrasetranslation",
            old_name="credits",
            new_name="num_credits",
        ),
        migrations.RenameField(
            model_name="sentencetranrequest",
            old_name="date_created",
            new_name="date_requested",
        ),
        migrations.RenameField(
            model_name="sentencetranrequest",
            old_name="creator",
            new_name="requestor",
        ),
        migrations.RenameField(
            model_name="sentencetranslation",
            old_name="credits",
            new_name="num_credits",
        ),
        migrations.RenameField(
            model_name="wordtranrequest",
            old_name="date_created",
            new_name="date_requested",
        ),
        migrations.RenameField(
            model_name="wordtranrequest",
            old_name="creator",
            new_name="requestor",
        ),
        migrations.RemoveField(
            model_name="phrasetranrequest",
            name="response",
        ),
        migrations.RemoveField(
            model_name="sentencetranrequest",
            name="response",
        ),
        migrations.RemoveField(
            model_name="wordtranrequest",
            name="response",
        ),
        migrations.DeleteModel(
            name="PhraseRequest",
        ),
        migrations.DeleteModel(
            name="SentenceRequest",
        ),
        migrations.DeleteModel(
            name="WordRequest",
        ),
        migrations.AddField(
            model_name="wordtranresponse",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="base.wordtranrequest"
            ),
        ),
        migrations.AddField(
            model_name="wordtranresponse",
            name="responsor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="sentencetranresponse",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="base.sentencetranrequest",
            ),
        ),
        migrations.AddField(
            model_name="sentencetranresponse",
            name="responsor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="sentencetrancredit",
            name="translation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="base.sentencetranslation",
            ),
        ),
        migrations.AddField(
            model_name="sentencetrancredit",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="phrasetranresponse",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="base.phrasetranrequest"
            ),
        ),
        migrations.AddField(
            model_name="phrasetranresponse",
            name="responsor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="phrasetrancredit",
            name="translation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="base.phrasetranslation"
            ),
        ),
        migrations.AddField(
            model_name="phrasetrancredit",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
