# Generated by Django 4.1.2 on 2022-11-10 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0054_newphrase_newphrasecredit_newsentence_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.course"
                    ),
                ),
            ],
            options={
                "db_table": "duoduo_role_course",
            },
        ),
        migrations.RemoveField(
            model_name="usermoderator",
            name="moderator",
        ),
        migrations.RemoveField(
            model_name="usermoderator",
            name="user",
        ),
        migrations.RemoveField(
            model_name="role",
            name="course",
        ),
        migrations.DeleteModel(
            name="Moderator",
        ),
        migrations.DeleteModel(
            name="UserModerator",
        ),
        migrations.AddField(
            model_name="rolecourse",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="base.role"
            ),
        ),
    ]
