# Generated by Django 4.1.2 on 2022-11-27 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0057_rename_lesson_collection_remove_newphrase_creator_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=220, unique=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("num_credits", models.IntegerField(default=0)),
                ("status_type", models.PositiveSmallIntegerField(default=0)),
                ("date_approved", models.DateTimeField(auto_now=True, null=True)),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.language",
                    ),
                ),
            ],
            options={
                "db_table": "duoduo_new_word",
            },
        ),
        migrations.CreateModel(
            name="NewWordTran",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("translation", models.JSONField(blank=True, default=dict, null=True)),
                ("num_credits", models.IntegerField(default=0)),
                ("status_type", models.PositiveSmallIntegerField(default=0)),
                ("date_approved", models.DateTimeField(auto_now=True, null=True)),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.course",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "new_word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.newword"
                    ),
                ),
            ],
            options={
                "db_table": "duoduo_new_word_translation",
            },
        ),
        migrations.CreateModel(
            name="WordTranRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now=True)),
                (
                    "old_translation",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "new_translation",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("change_logs", models.JSONField(blank=True, default=list, null=True)),
                ("approve", models.BooleanField(default=False)),
                ("date_approved", models.DateTimeField(auto_now=True, null=True)),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.course",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "translation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.wordtranslation",
                    ),
                ),
            ],
            options={
                "db_table": "duoduo_word_translation_revision",
            },
        ),
        migrations.CreateModel(
            name="WordTranRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request", models.TextField(blank=True, max_length=2020, null=True)),
                ("date_requested", models.DateTimeField(auto_now_add=True)),
                ("status_type", models.PositiveSmallIntegerField(default=0)),
                ("response", models.TextField(blank=True, max_length=2020, null=True)),
                ("date_responsed", models.DateTimeField(auto_now=True, null=True)),
                (
                    "requestor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responsor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "translation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.wordtranslation",
                    ),
                ),
            ],
            options={
                "db_table": "duoduo_word_translation_request",
            },
        ),
        migrations.CreateModel(
            name="NewWordTranCredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vote", models.BooleanField(default=False)),
                (
                    "translation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.newwordtran",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "duoduo_new_word_translation_credit",
            },
        ),
        migrations.CreateModel(
            name="NewWordCredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vote", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.newword"
                    ),
                ),
            ],
            options={
                "db_table": "duoduo_new_word_credit",
            },
        ),
        migrations.CreateModel(
            name="CollectionReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_reviewd", models.DateTimeField(auto_now_add=True)),
                ("review", models.TextField(blank=True, max_length=2020, null=True)),
                ("rating_value", models.SmallIntegerField(default=0)),
                (
                    "collection",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.collection",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "duoduo_collection_review",
                "unique_together": {("reviewer", "collection")},
            },
        ),
        migrations.CreateModel(
            name="CollectionLearning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_learned", models.DateTimeField(auto_now_add=True)),
                (
                    "collection",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.collection",
                    ),
                ),
                (
                    "learner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "duoduo_collection_learning",
                "unique_together": {("learner", "collection")},
            },
        ),
    ]
