# Generated by Django 4.1.2 on 2022-12-11 11:14

import base.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0058_newword_newwordtran_wordtranrevision_wordtranrequest_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wordtranrevision",
            old_name="change_logs",
            new_name="request_logs",
        ),
        migrations.RemoveField(
            model_name="wordtranrevision",
            name="old_translation",
        ),
        migrations.AddField(
            model_name="wordtranrequest",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base.course",
            ),
        ),
        migrations.AlterField(
            model_name="newword",
            name="status_type",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="newwordtran",
            name="status_type",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                default="avatars/default/default.webp",
                max_length=2020,
                upload_to=base.models.avatar_uploads2,
            ),
        ),
        migrations.AlterField(
            model_name="verification",
            name="type_verification",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="wordtranrequest",
            name="status_type",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="BlackList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=2020, null=True)),
                ("level", models.SmallIntegerField(default=0)),
                ("date_released", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "duoduo_blacklist",
            },
        ),
    ]
