# Generated by Django 4.1.2 on 2022-12-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0059_rename_change_logs_wordtranrevision_request_logs_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="cefr_level",
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
