# Generated by Django 4.1.2 on 2023-01-03 17:15

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0061_rename_is_completed_verification_is_verified_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blacklist",
            old_name="level",
            new_name="severity",
        ),
        migrations.AddField(
            model_name="blacklist",
            name="date_banned",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="avatars/default/default.webp",
                max_length=2020,
                null=True,
                upload_to=base.models.avatar_uploads2,
            ),
        ),
    ]
